# Generated by Django 3.2 on 2021-04-25 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pichapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activo')),
                ('is_open', models.BooleanField(default=True, verbose_name='Está abierto')),
                ('current_size', models.IntegerField(default=0, verbose_name='Participantes actuales')),
                ('max_size', models.IntegerField(verbose_name='Participantes máximos')),
                ('place', models.CharField(max_length=255, verbose_name='Lugar')),
                ('activity_datetime', models.DateTimeField(verbose_name='Fecha del encuentro')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pichapp.activitycategory')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
