# Generated by Django 3.2 on 2021-04-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pichapp', '0002_activitycategory_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
