# Generated by Django 3.2 on 2021-06-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pichapp', '0002_auto_20210614_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='image',
            field=models.ImageField(null=True, upload_to='pichapp/media', verbose_name='Imagen'),
        ),
    ]
