# Generated by Django 3.2 on 2021-04-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pichapp', '0003_alter_activitycategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycategory',
            name='verbose_name',
            field=models.CharField(default='No tengo nombre:(', max_length=255, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Nombre de código'),
        ),
    ]
