# Generated by Django 3.2 on 2021-04-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pichapp', '0005_alter_room_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Salita', max_length=255),
            preserve_default=False,
        ),
    ]
