# Generated by Django 3.2 on 2021-04-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pichapp', '0006_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='place',
        ),
        migrations.AddField(
            model_name='room',
            name='comuna',
            field=models.CharField(default='', max_length=255, verbose_name='Comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='meeting_place',
            field=models.CharField(default='', max_length=255, verbose_name='Lugar de encuentro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='region',
            field=models.CharField(default='', max_length=255, verbose_name='Región'),
            preserve_default=False,
        ),
    ]
