# Generated by Django 3.2 on 2021-06-23 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pichapp', '0008_alter_room_current_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='image',
            field=models.ImageField(null=True, upload_to='pichapp/media', verbose_name='Imagen'),
        ),
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pichapp.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
